parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: hermes_test
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 53467db1b5cb9dfeca561bda7970f61a275be7b6
